# -*- coding: utf-8 -*-
"""transformer custom training question answer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18GtZNzBzQ2aJW8UblV6QI2LRxEp1qL6k
"""

!pip install simpletransformers

import json
with open(r'train.json','r') as read_file:
  train = json.load(read_file)
train

with open(r'test.json','r') as read_file:
  test = json.load(read_file)
test

import logging
from simpletransformers.question_answering import QuestionAnsweringArgs, QuestionAnsweringModel

model_args = QuestionAnsweringArgs()
model_args.train_batch_Size = 16
model_args.evaluate_during_training = True
model_args.n_best_size = 3
model_args.num_train_epochs = 20

!pip install  wandb

model = QuestionAnsweringModel(model_type = 'bert',model_name ='bert-base-cased',args = model_args)

!rm -rf outputs

model.train_model(train,eval_data=test)

result, text = model.eval_model(test)

result

text

#predictions
 to_predict = [
            {
                "context": "Vin is a Mistborn of great Power and skill.",
             "qas":[
                   {
                       "question":"what is vin's speciality?",
                    "id":"0",
                   }
             ],
            }
 ]

answer,probab = model.predict(to_predict)
print(answer)

